version: '3'

services:
  api:
    container_name: tasks-tracker-api
    build: ./server
    command: yarn start
    restart: always
    ports:
      - 5003:5003
    env_file:
      - /server/.production.env
    depends_on:
      - api_db
    networks:
      - tasks-tracker-network

  api_db:
    container_name: tasks-tracker-api-db
    image: postgres:14-alpine
    restart: always
    env_file:
      - /server/.production.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - postgres_api:/var/lib/postgresql/data
    networks:
      - tasks-tracker-network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - /server/.production.env
    ports:
      - 5050:80
    networks:
      - tasks-tracker-network

volumes:
  postgres_api:

networks:
  tasks-tracker-network:
    driver: bridge