version: '3'

services:
  api:
    command: yarn start:dev
    ports:
      - 5000:5000
      - 9229:9229
    env_file:
      - /server/.env
    volumes:
      - ./server/src:/usr/src/app/src
      - ./server/node_modules:/usr/src/app/node_modules

  api_db:
    env_file:
      - /server/.env

  pgadmin:
    env_file:
      - /server/.env